# Generated by Django 5.2.8 on 2025-12-18 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_exam_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('overall_performance', models.CharField(choices=[('excellent', 'Excellent (90-100)'), ('good', 'Good (80-89)'), ('average', 'Average (70-79)'), ('pass', 'Pass (60-69)'), ('fail', 'Fail (<60)')], default='pass', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='project_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip', 'rar'])])),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('late', 'Late Submission')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-submission_date'],
                'indexes': [models.Index(fields=['student', 'status'], name='reports_pro_student_c1d08b_idx')],
            },
        ),
    ]
