# Generated by Django 5.2.8 on 2026-01-05 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_department_update_subject'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='exams_depar_code_19442e_idx',
            old_name='exams_depart_code_idx',
        ),
        migrations.RenameIndex(
            model_name='subject',
            new_name='exams_subje_departm_b41d6d_idx',
            old_name='exams_subje_departm_idx',
        ),
    ]
